# Generated by Django 2.2.1 on 2019-05-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0009_auto_20190516_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(choices=[('In Queue', 'In Queue'), ('Complete', 'Complete')], default='In Queue', max_length=30),
        ),
    ]
