# Generated by Django 2.2.1 on 2019-05-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0010_auto_20190516_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='unit_title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
