# Generated by Django 2.2.1 on 2019-07-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0014_remove_transcript_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.Semester')),
                ('transcript', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf.Transcript')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.Unit')),
            ],
        ),
    ]
