# Generated by Django 2.2.1 on 2019-07-10 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0016_lecturer_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='transcript',
        ),
    ]
