# Generated by Django 2.2.1 on 2019-07-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0017_remove_lecturer_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='cat',
            field=models.DecimalField(decimal_places=1, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='final',
            field=models.DecimalField(decimal_places=1, max_digits=13, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='grade',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
